version: '3'

services:
  backend:
    image: node:10.16.0-stretch
    working_dir: /code
    command: [
      "./wait-for-it.sh", 
      "db:3306", 
      "--",
      "npm",
      "run",
      "dev"
    ]
    environment:
      PORT: 8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    networks: 
      - backend
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7.26
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=pa55w0rd11
    networks: 
      - db

networks: 
  backend:
  db: